int [] arr = new int [5];
arr [0] = 4;
arr [1] = 91;
arr [2] = 26;
arr [3] = 67;
arr [4] = 14;
Console.WriteLine(arr[0]);
System.Console.WriteLine(arr[1]);
System.Console.WriteLine(arr[2]);
System.Console.WriteLine(arr[3]);
System.Console.WriteLine(arr[4]);
